# Generated by Django 5.2.5 on 2025-09-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(default='Remote', max_length=100)),
                ('job_type', models.CharField(default='Full-time', max_length=100)),
                ('salary_range', models.CharField(max_length=50)),
                ('posted_days', models.CharField(default='1 day ago', max_length=50)),
                ('openings', models.IntegerField(default=1)),
                ('applicants', models.IntegerField(default=0)),
                ('responsibilities', models.TextField(help_text='Use line breaks for bullet points')),
                ('role', models.CharField(max_length=100)),
                ('candidate_type', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('skills', models.CharField(help_text='Comma separated skills', max_length=300)),
                ('about_company', models.TextField()),
            ],
        ),
    ]
