# Generated by Django 5.2.5 on 2025-09-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('languages', models.CharField(max_length=255)),
                ('work_status', models.CharField(max_length=200)),
                ('experience_years', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=200)),
                ('passed_out_year', models.CharField(max_length=4)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('updates_optin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
