# Generated by Django 5.2.5 on 2025-09-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userprofile_user_userprofile_work_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(default='Yearly', max_length=50)),
                ('features', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='plan_images/')),
            ],
        ),
    ]
