# Generated by Django 5.2.5 on 2025-09-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='image',
        ),
        migrations.AddField(
            model_name='plan',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.TextField(help_text='Comma separated features'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
