# Generated by Django 5.2.5 on 2025-09-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_plan_image_plan_is_current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('video_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('doubt_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='tool_icons/')),
                ('pdf_file', models.FileField(upload_to='interview_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='JobVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='job_videos/')),
                ('video_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PlacementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('session_type', models.CharField(default='1 to 1 Session', max_length=50)),
                ('mode', models.CharField(default='Online (Microsoft Teams)', max_length=100)),
            ],
        ),
    ]
