# Generated by Django 5.2.5 on 2025-09-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_coursetopic_doubt_interviewquestion_jobvideo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetopic',
            options={'ordering': ['order'], 'verbose_name': 'Course Tools Topics', 'verbose_name_plural': 'Course Tools Topics'},
        ),
        migrations.AlterModelOptions(
            name='doubt',
            options={'verbose_name': 'doubt clear form', 'verbose_name_plural': 'doubt clear form'},
        ),
        migrations.AlterModelOptions(
            name='interviewquestion',
            options={'verbose_name': 'Interview questions & Pdf add', 'verbose_name_plural': 'Interview questions & Pdf add'},
        ),
        migrations.AlterModelOptions(
            name='jobvideo',
            options={'verbose_name': 'job video upload', 'verbose_name_plural': 'job video upload'},
        ),
        migrations.AlterModelOptions(
            name='placementsession',
            options={'verbose_name': 'placement session Date & Time ', 'verbose_name_plural': 'placement session Date & Time'},
        ),
        migrations.RemoveField(
            model_name='coursetopic',
            name='video_link',
        ),
    ]
