# Generated by Django 5.2.5 on 2025-09-09 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_coursetopic_options_alter_doubt_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Course name',
                'verbose_name_plural': 'Courses name',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='myapp.course')),
            ],
            options={
                'verbose_name': 'Course Topic',
                'verbose_name_plural': 'Course Topics',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='CourseTopic',
        ),
    ]
