# Generated by Django 5.2.5 on 2025-09-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_course_topic_delete_coursetopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order'], 'verbose_name': 'Course Topic adding section', 'verbose_name_plural': 'Course Topics adding section '},
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
