# Generated by Django 5.2.5 on 2025-09-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_topic_options_alter_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
