# Generated by Django 5.2.5 on 2025-09-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_topic_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
