# Generated by Django 5.2.5 on 2025-09-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_topic_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='video_thumbnail',
        ),
        migrations.AddField(
            model_name='course',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
    ]
