# Generated by Django 5.2.5 on 2025-09-09 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_topic_video_thumbnail_course_video_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doubt',
            options={'verbose_name': 'Doubt Clear Form', 'verbose_name_plural': 'Doubt Clear Forms'},
        ),
        migrations.AlterModelOptions(
            name='interviewquestion',
            options={'verbose_name': 'Interview Questions & PDF', 'verbose_name_plural': 'Interview Questions & PDF'},
        ),
        migrations.AlterModelOptions(
            name='jobvideo',
            options={'verbose_name': 'Job Video Upload', 'verbose_name_plural': 'Job Video Uploads'},
        ),
        migrations.AlterModelOptions(
            name='placementsession',
            options={'verbose_name': 'Placement Session Date & Time', 'verbose_name_plural': 'Placement Sessions Date & Time'},
        ),
        migrations.AddField(
            model_name='doubt',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='myapp.course'),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='myapp.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobvideo',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_videos', to='myapp.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placementsession',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='placement_sessions', to='myapp.course'),
            preserve_default=False,
        ),
    ]
