# Generated by Django 5.2.5 on 2025-09-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_doubt_options_alter_interviewquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobvideo',
            name='video_link',
        ),
        migrations.AddField(
            model_name='jobvideo',
            name='video_file',
            field=models.FileField(null=True, upload_to='job_videos/'),
        ),
        migrations.AlterField(
            model_name='jobvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='job_video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='jobvideo',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
