# Generated by Django 5.2.5 on 2025-09-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_jobvideo_video_link_jobvideo_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='myapp.course'),
        ),
    ]
