# Generated by Django 5.2.5 on 2025-09-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_job_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_tools',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
