# Generated by Django 5.2.5 on 2025-09-10 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_course_course_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.course'),
        ),
    ]
