# Generated by Django 5.2.5 on 2025-09-11 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_job_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job vaccuncy Details Upload section', 'verbose_name_plural': 'Job vaccuncy Details Upload section'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plan Details Upload', 'verbose_name_plural': 'Plan Details Upload'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order'], 'verbose_name': 'Course Topics adding section', 'verbose_name_plural': 'Courses Topics adding section '},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.plan'),
        ),
    ]
