# Generated by Django 5.2.5 on 2025-09-11 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_job_options_alter_plan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='plan',
        ),
    ]
