# Generated by Django 5.2.5 on 2025-09-11 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_userprofile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.plan'),
        ),
    ]
