# Generated by Django 5.2.5 on 2025-09-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_application_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='plan',
        ),
    ]
