# Generated by Django 5.2.5 on 2025-09-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_application_user_userprofile_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='plan_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='plan_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
